### ISSUE TITLE
Make all documented `cohortextractor` examples use compressed format

### ISSUE THREAD

**Issue by alexwalkerepi** [opensafely/documentation#1063]
In the primary description of `cohortextractor` actions [here](https://docs.opensafely.org/actions-cohortextractor/#generate_cohort) it correctly uses `.csv.gz`, but in at least [one other place](https://docs.opensafely.org/study-def/#multiple-study-definitions), it uses `.csv`.

**Comment by StevenMaude** [comment]
The unmerged #656 may partially cover this already.

**Comment by StevenMaude** [comment]
#656 is now merged. So this should be re-reviewed.
