### ISSUE TITLE
Add a "releasing your project" section

### ISSUE THREAD

**Issue by sebbacon** [opensafely/documentation#107]
For example, it should cover:

* Amending or adding a LICENCE file (MIT licence recommended; Open-Source compatible required)
* Making repo public
* Updating README including "how to cite" section
* Making a "release" so it's clear which version related to the paper / publication that references it
* Obtaining a DOI

**Comment by brianmackenna** [comment]
Having done a few of these I think "when" is important as well. Unless a very good reason for a specific project I propose that GH repos should be made public at the same time as you submit to MedRxiv.

MedRxiv generally takes 1-4 days - this allows time to tweak repor, spot typo, broken urls. It alos means we don't have to be publically reminded on Twitter to make it public as don't get exact notice of  MedRxiv making it live.

**Comment by brianmackenna** [comment]
Having done two releases in past 24 hours other things that could be considered
- reviewing issues to see if any can be closed
- reviewing branches to see if they can be deleted

I'm not sure what best practice is but I think doing this will just make the repos a bit tidier.

**Comment by StevenMaude** [comment]
@annaschultze in [this comment](https://github.com/opensafely/documentation/issues/185#issue-830103763
):
> This may well be classed as something that should fall under people's existing git knowledge, but personally would find it super useful if there was a guide somewhere for the steps one would typically go through before making a repo public, and when we expect things to be made public in the OS workflow.
> 
> For example, I know how to make a repo public, that this happens when I preprint and that I need to update the README, but I'm unsure about the role of releases and when we'd typically use those...
