### ISSUE TITLE
Fix: Index date currently string rather than variable name in pseudo code

### ISSUE THREAD

**Issue by jogilder** [opensafely/documentation#108]
https://docs.opensafely.org/en/latest/study-def/
6th code block needs correction of last line

`age = patients.age_as_of("index_date")`

should be

`age = patients.age_as_of(index_date)`

**Comment by madwort** [comment]
Thanks for the report - I've filed a PR to amend this.

**Comment by wjchulme** [comment]
Closing this issue - see https://github.com/opensafely/documentation/pull/109#issuecomment-764802645
