### ISSUE TITLE
Consider skipping Data Builder documentation link checks here

### ISSUE THREAD

**Issue by StevenMaude** [opensafely/documentation#1159]
We now check them in the [Data Builder repository](https://github.com/opensafely-core/databuilder/pull/1124).

Reasons to do so:
* we may be able to remove any duplicated `.lycheeignore` lines in both repositories to cover the same exceptions (there may be some unavoidable duplication due to accessing the same URL or domain)
* it means we only get notified for link failures in one place, for each kind of content (main documentation, and Data Builder documentation)

I think Lychee's `--exclude-path` option will fix this.

**Comment by StevenMaude** [comment]
We can try leaving this as is for now, as suggested by @rebkwok, and revisit if it's useful.

**Comment by rebkwok** [comment]
I've realised that the `check_links` workflow here doesn't check databuilder docs anyway, because it doesn't build, so it doesn't pull in any of the imported docs before running the checks.
