### ISSUE TITLE
Remove references to Gitpod

### ISSUE THREAD

**Issue by rebkwok** [opensafely/documentation#1173]
**Update**: we now want to remove Gitpod entirely.

---

@brianmackenna pointed out that the [getting started guide](https://docs.opensafely.org/getting-started/#options-for-running-opensafely) in the docs implies that gitpod is the preferred method of running OpenSAFELY. It currently is not - at least not for committed users.  If we continue to support gitpod we may want to consider:

- stating clearly that approved OpenSAFELY users (as opposed to interested parties just having a look at the tool) should aim to use a local install if possible
- Switching the order of either the introduction to the options, or the tabs (or both) so that the local install options are shown first

**Comment by StevenMaude** [comment]
Relatedly, I'd add that:

* the Getting Started guide might actually want to put "run in Codespaces" as the primary way of seeing how things work (which is what the ehrQL tutorial does), and making "install on your own machine" a further step, given the complications we've seen for local installs [^1]
* a fair chunk of the initial ehrQL tutorial likely overlaps with the Getting Started guide

[^1]: Specifically: user lack of administrative rights; Docker issues on Windows/macOS; quirks of Python installations

**Comment by ghickman** [comment]
This landed on the pipeline board, but we're pretty sure it's a data team task, do shout if we've misunderstood something!

**Comment by StevenMaude** [comment]
This came up again today: https://bennettoxford.slack.com/archives/C63UXGB8E/p1700731771623999?thread_ts=1698849577.197769&cid=C63UXGB8E
