### ISSUE TITLE
Error in example code for date_deregistered_from_all_supported_practices

### ISSUE THREAD

**Issue by kevwing** [opensafely/documentation#1217]
Hi,

There is an error in the example code for the `date_deregistered_from_all_supported_practices` example in the documentation ("-DD" is missing from date_format).

The current code example is:

```
dereg_date=patients.date_deregistered_from_all_supported_practices(
    on_or_after="2020-03-01",
    date_format="YYYY-MM",
    return_expectations={
        {"date": {"earliest": "2020-03-01"},
        "incidence": 0.05
    }
)
```

but should be:

```
dereg_date=patients.date_deregistered_from_all_supported_practices(
    on_or_after="2020-03-01",
    date_format="YYYY-MM-DD",
    return_expectations={
        {"date": {"earliest": "2020-03-01"},
        "incidence": 0.05
    }
)
```
Thanks, Kevin

**Comment by inglesp** [comment]
Hi Kev -- thanks for your suggestion.  The example is not incorrect, in the sense that `YYYY-MM` is a valid value for the `date_format` argument (it rounds dates to the first of the month) -- but this has been a source of confusion, so I've updated the docs to use `YYYY-MM-DD` in most cases.  (See https://github.com/opensafely-core/cohort-extractor/pull/950.)
