### ISSUE TITLE
Ensure stylesheet from ehrQL docs gets included

### ISSUE THREAD

**Issue by evansd** [opensafely/documentation#1235]
The ehrQL documentation includes a [custom stylesheet](https://github.com/opensafely-core/ehrql/blob/36982b33622d9cef16b74af027e3413e7d03ad0c/docs/stylesheets/extra.css) configured here:
https://github.com/opensafely-core/ehrql/blob/36982b33622d9cef16b74af027e3413e7d03ad0c/mkdocs.yml#L20-L21
```yaml
extra_css:
  - stylesheets/extra.css
```

But this does not get automatically included when the ehrQL docs are embedded in main documentation. Compare, e.g., these pages:
https://docs.opensafely.org/data-builder/schemas/beta.core/#clinical_events
https://evansd-schema-docs.databuilder.pages.dev/schemas/beta.core/#clinical_events

**Comment by StevenMaude** [comment]
This is slightly more complicated than merely adding a configuration setting unfortunately, because MkDocs requires that `extra_css` files are in the `docs_dir`:

https://github.com/mkdocs/mkdocs/issues/1662

With the multi-repository build, the structure is like:

```
documentation
|
|\
| docs — contains the main CSS in `./css/`
| …
|\
| imported-docs — contains additional CSS in `./imported_docs/data-builder/stylesheets`
```
```
