### ISSUE TITLE
Fix automated deploy

### ISSUE THREAD

**Issue by madwort** [opensafely/documentation#127]
@madwort has started doing this https://github.com/opensafely/documentation/issues/106 but it's not working, please deploy manually in the mean-time!

**Comment by sebbacon** [comment]
Bizarrely, it's failing with a failure to build matplotlib...

**Comment by ghickman** [comment]
@sebbacon testing 1 2 1 2

**Comment by madwort** [comment]
`RuntimeError: Broken toolchain: cannot link a simple C program` I haven't looked properly, but my assumption is [the docker image it's running the build on](https://github.com/mhausenblas/mkdocs-deploy-gh-pages/blob/master/Dockerfile#L1) doesn't have buildtools / libs we need for our excessive mkdocs dependencies

**Comment by madwort** [comment]
I think we need this: https://github.com/mhausenblas/mkdocs-deploy-gh-pages/pull/74

**Comment by madwort** [comment]
It works! It only takes 1hr 1m to complete...! 
https://github.com/opensafely/documentation/actions/runs/555800853

**Comment by madwort** [comment]
I guess we could use a docker image with a bunch of stuff built in, if we want to speed things up

**Comment by madwort** [comment]
replace with https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-static-site-generators-with-python

**Comment by madwort** [comment]
yep that works sooooo much better
