### ISSUE TITLE
Minor fix: maximum_of() is repeated

### ISSUE THREAD

**Issue by HelenCEBM** [opensafely/documentation#129]
Should one instance be `minimum_of()`?
![image](https://user-images.githubusercontent.com/24392156/107067239-e8b88080-67d6-11eb-85a1-c3f65d625759.png)

https://docs.opensafely.org/en/latest/study-def-variables/#cohortextractor.patients.maximum_of

**Comment by wjchulme** [comment]
it sure should https://github.com/opensafely/documentation/pull/130
