### ISSUE TITLE
EHRQL doc typo

### ISSUE THREAD

**Issue by rose-higgins** [opensafely/documentation#1312]
The example at the very end of [this page](https://docs.opensafely.org/ehrql/tutorial/dataset-definition-concepts/#explaining-the-example) needs to be `latest_asthma_med` instead of [latest_asthma_medication]

![image](https://github.com/opensafely/documentation/assets/95700645/4860d191-94e8-4f59-86fe-073fae9a9c98)

**Comment by StevenMaude** [comment]
@rose-higgins: thank you for the suggested correction! :mag:

I've made your fix in https://github.com/opensafely-core/ehrql/pull/1504 which will fix it in the documentation once it's merged.

**Comment by StevenMaude** [comment]
Now deployed.
