### ISSUE TITLE
Clarify the EMIS wait

### ISSUE THREAD

**Issue by sebbacon** [opensafely/documentation#1330]
Currently, our hands are tied by funding arrangements. We should make that clear, by changing the warnings in these two places:

1. https://docs.opensafely.org/data-sources/emis/
1. https://docs.opensafely.org/ehrql/reference/backends/

Suggested text:

> Research access to the backend provided by EMIS is temporarily unavailable, pending funding arrangements between NHS England and EMIS. When funding has been secured, we will publish a timeline for gradually reopening access. 

The first page can probably lose the non-warning text; certainly the first paragraph, which is now legacy information. The second paragraph feels somewhat out-of-place, but addressing this ticket does not require that to be moved.

**Comment by StevenMaude** [comment]
1. Fixed by #1331.
2. (to change in ehrQL docs; will edit when done)

**Comment by StevenMaude** [comment]
Merged the two PRs, so this is complete now.
