### ISSUE TITLE
Search returns "raw" schemas before other schemas

### ISSUE THREAD

**Issue by evansd** [opensafely/documentation#1455]
Searching for tables which appear in both "cooked" and "raw" schemas returns the raw schema first, which confuses users.

For example:
![image](https://github.com/opensafely/documentation/assets/19630/dba6106c-9314-45e5-ba7e-31bb9048acc0)

Thread where this confusion arose:
https://bennettoxford.slack.com/archives/C04DVD1UQC9/p1709896596557359

**Comment by StevenMaude** [comment]
The developers of Material for MkDocs are working on an [improved search feature](https://github.com/squidfunk/mkdocs-material/issues/6307), which might help here.

As a shorter term solution, perhaps [manually adjusting the search boost](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-boosting) to derank one page relative to the other might be worth testing out.

**Comment by evansd** [comment]
Closing in favour of https://github.com/opensafely-core/ehrql/issues/2086 (I'd have just transferred the issue but it's a different org so that's not possible).
