### ISSUE TITLE
Copying Python code blocks includes ">>>"

### ISSUE THREAD

**Issue by Jongmassey** [opensafely/documentation#1458]
From the ehrQL tutorial:

>Notice that the command prompt, or the set of characters before the cursor, has changed to >>>. For the remainder of this section, when you see >>>, you should type the code that follows into the sandbox and press Enter.

The "copy" button next to the code blocks puts the full contents of the box including the `>>>` onto the clipboard - could we modify the behaviour such that it doesn't?

**Comment by Jongmassey** [comment]
This looks like it is [a known issue ](https://github.com/squidfunk/mkdocs-material/issues/3647)with no easy solution in mkdocs-material

Preventing user selection of the `>>>` and `...` elements [is more possible](https://mkdocstrings.github.io/recipes/#prevent-selection-of-prompts-and-output-in-python-code-blocks) and may be a worthwhile improvement.

**Comment by StevenMaude** [comment]
Relatedly, this is also an issue with [copy-pasting of terminal commands](https://github.com/opensafely-core/codespaces-initiative/issues/30), a reader has to remove the `$` themselves.

Or we remove them entirely from the text. But that's at the expense of making it less obvious which commands are for the terminal.

I'm not sure there's anyway of separating out the prompt in the same way; if there is, something similar might be a nice way to do so.

**Comment by Jongmassey** [comment]
with the `sh` short code it doesn't but with `shell-session` it does, we should use the latter where we are expecting the user to enter commands in an interactive terminal

**Comment by StevenMaude** [comment]
> with the `sh` short code it doesn't but with `shell-session` it does, we should use the latter where we are expecting the user to enter commands in an interactive terminal

That's a good find!
