### ISSUE TITLE
Restructure Viewing and releasing outputs section

### ISSUE THREAD

**Issue by rebkwok** [opensafely/documentation#1615]
I have a suggestion about organisation. Much of the focus here is on *releasing* outputs. However, the very first thing users will want to do is look at at outputs, before they ever get to releasing.

As such, I wonder if this menu structure:

* Releasing research outputs
  * Applying statistical disclosure control
  * Requesting release of research outputs
  * Review process for release requests
  * Viewing released outputs
  * Releasing with Airlock >
  
could possibly restructure/renamed, possibly with a new section, something like:

* Viewing and Releasing Outputs
  * *Viewing outputs with Airlock* 
  * Applying statistical disclosure control
  * Requesting release of research outputs
  * Review process for release requests
  * Viewing released outputs
  * Viewing and Releasing with Airlock >  
  
The new section would mostly be pointers to airlock docs, but it could cover things like where to look for job logs and such also?
 
This may be a latter thing to think about. But I think that viewing outputs is really important first concept.

_Originally posted by @bloodearnest in https://github.com/opensafely/documentation/pull/1594#pullrequestreview-2268668068_

**Comment by khaleel2788** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by remlapmot** [comment]
This comment by @khaleel2788 I've just hidden and marked as spam likely contains a link to malware. This looks very similar to the attack on GitHub about 2 weeks ago in which malware links were spread in comments using compromised GitHub accounts. Recommend deleting it. @bloodearnest @inglesp

**Comment by evansd** [comment]
Once the "Viewing outputs with Airlock" section exists we should consider updating the link here to point to it:
https://github.com/opensafely-core/job-server/blob/438b49cbb44739a582e51756560a40706d65e267/templates/job/detail.html#L145
