### ISSUE TITLE
Confusing prompt for additional permissions during the getting started tutorial

### ISSUE THREAD

**Issue by iaindillingham** [opensafely/documentation#1623]
The getting started tutorial asks the user to [start a Codespace](https://docs.opensafely.org/getting-started/tutorial/create-a-github-codespace/) in a repo that was created from the research template. Having started a Codespace, and assuming the user's browser doesn't hand over to VS Code, the user is then prompted to authorise (or not) additional permissions. Whilst we have documented the prompt on the "[How to troubleshoot common issues in GitHub Codespaces](https://docs.opensafely.org/getting-started/how-to/troubleshoot-common-codespaces-issues/)" page, it's unlikely that the user will have read this page before starting the tutorial. Consequently, the prompt is confusing.

The prompt asks the user to authorise read permissions for [opensafely/server-instructions](https://github.com/opensafely/server-instructions), which is a private repository. The user is prompted even when they're _not_ a member of opensafely, as @Mary-Anya discovered. I'm surprised by this -- surely if the user isn't a member of opensafely, then they shoulnd't know about a private repository associated with opensafely.

We could...

* mention the prompt when the user is asked to start a Codespace
* start the Codespace with default permissions. (This is possible with [`gh codespace create`](https://cli.github.com/manual/gh_codespace_create).)

**Comment by iaindillingham** [comment]
Martina asked about the prompt on Slack[^1] today. Thanks for answering her question, @Jongmassey.

[^1]: https://bennettoxford.slack.com/archives/C01D7H9LYKB/p1726838657270489

**Comment by Jongmassey** [comment]
It also might be possible to negate the need for this cross-repository permission by making using of a pre-existing organisation secret to set the env var required to make Stata play nice
