### ISSUE TITLE
Improvements to the getting started tutorial

### ISSUE THREAD

**Issue by iaindillingham** [opensafely/documentation#1626]
Couple of suggestions from @Mary-Anya[^1] for the getting started tutorial:

* [Create a GitHub repository](https://docs.opensafely.org/getting-started/tutorial/create-a-github-repository/) at the bottom, "Create Repository from template" is now 'Create Repository'. The text and the screenshot should be updated.

* [Run the project pipeline](https://docs.opensafely.org/getting-started/tutorial/run-the-project-pipeline/) > Run the `project.yaml` file: add/repeat "Open project.yaml in the editor. This file will be near the end of the list of files and folders" - it's in the next section, but this is the first time you actually use the file.

[^1]: https://bennettoxford.slack.com/archives/C069SADHP1Q/p1726649680207919

**Comment by lucyb** [comment]
I have volunteered @eli-miriam to pick this up, as they plan on making some related wording changes to the Getting Started tutorial based on their recent experience of going through it.
