### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by HelenCEBM** [opensafely/documentation#165]
In [this section](https://docs.opensafely.org/en/latest/codelist-creation/#import-the-codelist-for-use-in-your-study-definition)
The link under `Follow these instructions` is dead (goes [here](https://github.com/opensafely/documentation/blob/master/Onboarding%20analysts.md#add-the-relevant-codelist-and-commit))

**Comment by madwort** [comment]
I just did a search in the git history for deleted files with `git log --diff-filter=D --summary  docs/`, which turns up https://github.com/opensafely/documentation/pull/51 , which moves the relevant doc from `docs` to `unused-docs`. 
So I guess the question is for @wjchulme - should we go ahead & reinstate this file in `docs`? Or should we remove the link?

**Comment by madwort** [comment]
Or missing option - inline the content from the old file into the file that linked to it.

**Comment by wjchulme** [comment]
I think this just needs a link to this page instead https://docs.opensafely.org/en/latest/codelist-project/ -- can do it when I'm back next week
