### ISSUE TITLE
De-dupe git info from Getting Started

### ISSUE THREAD

**Issue by madwort** [opensafely/documentation#179]
The next steps section of https://docs.opensafely.org/en/latest/getting-started/#5-next-steps

---

You'll be using git and Github a lot, and it's a critical but complex part of the OpenSAFELY ecosystem. If you're not familiar with these concepts, it's a good idea to read some of the official Github guides, starting with the Hello World tutorial. If you prefer learning via video, there is also a Github Youtube Channel.

---

mildly duplicates the content of https://docs.opensafely.org/en/latest/git-workflow/  - should we refactor to merge all content onto the git-workflow page & link to it from the end of getting-started?

**Comment by sebbacon** [comment]
I think that's a good idea, but as there's loads of that sort of docs-review work to do, I won't be doing it today... :)
