### ISSUE TITLE
Proposal: Add info on making repos public

### ISSUE THREAD

**Issue by annaschultze** [opensafely/documentation#185]
This may well be classed as something that should fall under people's existing git knowledge, but personally would find it super useful if there was a guide somewhere for the steps one would typically go through before making a repo public, and when we expect things to be made public in the OS workflow. 

For example, I know how to make a repo public, that this happens when I preprint and that I need to update the README, but I'm unsure about the role of releases and when we'd typically use those...

**Comment by StevenMaude** [comment]
I think this is mostly covered by #107, so closing this issue and copying the comment over to that issue.

Please reopen if there's something here that's not covered by that issue :slightly_smiling_face:
