### ISSUE TITLE
"Stable" URL Provides Stale Docs

### ISSUE THREAD

**Issue by ghickman** [opensafely/documentation#197]
Google has been surfacing links to the documentation in the format: https://docs.opensafely.org/en/stable/

Note the final `stable` section of the path.

However, when visiting https://docs.opensafely.org you get redirected to https://docs.opensafely.org/en/latest/

* Where does the stable URL and content come from?
* Can we redirect it to `latest` so Google URLs aren't broken?

**Comment by madwort** [comment]
We were under the mis-understanding that this was deployed on github pages, when it was actually deployed on readthedocs (RTD). RTD was creating the stable URL etc. Now removed & redirects for urls observed in Google added.
