### ISSUE TITLE
Add a build check on pull request

### ISSUE THREAD

**Issue by StevenMaude** [opensafely/documentation#223]
This would flag issues to a PR author and reviewer(s) before attempting to deploy a new version of the documentation

**Comment by madwort** [comment]
FWIW this is built by https://readthedocs.org/ currently using python-3.7

**Comment by StevenMaude** [comment]
In principle, we could use `mkdocs build --strict` now, since we have no build warnings now as of ebe012148f7b5a0edeb1fb152915fcbce27971fb.

Haven't used `mkdocs` enough to know if there are possible warnings that we are happy to ignore, however.

**Comment by madwort** [comment]
sounds good, let's go with `--strict`?

**Comment by StevenMaude** [comment]
:+1: @madwort: happy to take it and then let you review, if you like.
