### ISSUE TITLE
Adding ONS / CPNS / ITU / Hospital Admission / ECDS variables to docuemtnation 

### ISSUE THREAD

**Issue by CarolineMorton** [opensafely/documentation#26]
Currently we have clinical data from primary care and SGSS data.

**Comment by wjchulme** [comment]
I think the idea is that this will be covered by the docstrings in https://github.com/opensafely/cohort-extractor/blob/master/cohortextractor/patients.py ? see for example https://github.com/opensafely/cohort-extractor/pull/324

**Comment by wjchulme** [comment]
closed by https://github.com/opensafely/documentation/pull/40
