### ISSUE TITLE
Update Documentation Structure and Subheadings

### ISSUE THREAD

**Issue by annaschultze** [opensafely/documentation#265]
I know that I reviewed and approved the current structure and subtitling within the documentation, but having used the new layout for a while I think we could probably improve this further. The issues that I have spotted are: 

- Concepts of "Reference" and "How-to guides" mixed. It's unclear for example why codelists are in reference and not in the how-to section. 
- Assuming a user does not know whether to look at reference or how-to, they'll probably click on how-to first because it's at the top. This means that things that happen at the end of a project, such as releasing files from the server, is displayed before important information needed at the beginning of the project, such as the structure of the github repo. Within Reference the order is chronological though. 

I suggest: 

- Make most of the things in 'Reference' a How-to guide and display chronologically under How-to. This would likely require just changing the headings on some of the reference sections so that the names match what you're doing at that point in the project, for example, from 'Codelists' to 'Creating and Using OpenSAFELY Codelists', from 'Actions' to 'Running your code locally', from 'Job Server' to 'Running code against real data'. The aim would be that the how-to guides would move a reader from beginning of a project to the end in a logical flow that matches the typical opensafely workflow, and that headings do not contain information that's not obvious to new users (i.e, "Actions" may not be an obvious concept to many epis) 
- Retain only sections that relate to things a user might not have to do in every project in reference, i.e., the installation guide, some parts of text currently included under study definition (specifically, the variable reference and measures), and the data source descriptions. The idea is that when someone is doing an opensafely project, they would definitely have to go through a series of steps, such as using codelists, or running actions, but they wouldn't have to know all of the different variable options available within cohortextractor for example. 

This is really not an urgent suggestion and very happy to brainstorm further, it's mainly spurred by the number of times I've clicked on the wrong subheading recently...!

**Comment by StevenMaude** [comment]
Agree with @annaschultze's detailed feedback. There's room to streamline the structure and flows through the documentation. And the concepts of "reference"/"how to" are a jumble right now. If experienced users know a section is there and can't always easily find it again, this suggests that we can improve things.

Having a clear goal with each part of the documentation is really important: what type of document is this? A tutorial? Reference documentation? Background contextual information? A few of us at DataLab have mentioned the [Diátaxis Framework](https://diataxis.fr/) at times before, which puts that concept first. It might be something to consider trying out longer term. In the short term, we can reorganise the existing sections.

(Incidentally, it's great to get feedback from OpenSAFELY users, new or experienced. Myself and @bloodearnest did a couple of quick iterations on the revised Getting Started guide (#249) by running through it in sessions with a new and a experienced OpenSAFELY user in DataLab. I think if we have enough spare time and resources to do this, then there's definite value in us getting more feedback to improve the docs for its readers. I'm happy to discuss ideas for improvements in GitHub issues, or with people on Slack.)

**Comment by annaschultze** [comment]
I'd not heard about the Diataxis framework, but that looks really interesting! Seems like a great thing to attempt to follow. I think just moving some of the content around might be a relatively easy fix, but if there's a more major re-arrangement under way in the future it may not be worthwhile. 

And always interested in talking about this, as it turns out the structure of documentation is one of my interests :) Pending time and resources of course..!

**Comment by StevenMaude** [comment]
I think for the (small) work involved in moving sections, it's valid to do that now if it make things easier to find immediately :slightly_smiling_face:

**Comment by StevenMaude** [comment]
@HelenCEBM: Completely agree that "Reference" is now more cluttered and that some of those topics are actually core material needed to understand how to run a study. Likewise the "How to" is similarly "Miscellaneous". (This echoes what @annaschultze said in the [opening comment](https://github.com/opensafely/documentation/issues/265#issue-918963837) here.)

I think there's possibly a case for structuring the documentation more around the OpenSAFELY study process, from research problem to publication. Such a reordering might also provide a better logical flow for someone simply reading through the documentation sequentially, via the "next" links in the footer.

I don't think it would take much rearranging to be much better structured. However, I'd much prefer a researcher *actually using the docs to get research done* driving suggestions on improvements, over myself or another developer taking their best guess at what structure might work. Happy to pair on this and discuss more when we're both available to do so; please feel free to ask me if I forget! :+1:

**Comment by HelenCEBM** [comment]
I've made a suggested structure [here](https://docs.google.com/spreadsheets/d/1iLMXqXVTshyIoOUpM901Gk12C44my6VO91vEPEiqGkQ/edit#gid=0) - feel free to edit/comment/make a new one!

**Comment by annaschultze** [comment]
Thank you so much for taking this on @HelenCEBM, agree with you that structuring according to workflow seems the most intuitive to me. I've commented on your proposed structure: some of my comments relate to rewriting/adding content to the docs and can probably be ignored. 

Happy to join a call to brainstorm this if you'd like.

**Comment by StevenMaude** [comment]
@HelenCEBM: the structure you suggested looks good to me.

I would suggest the next step is that you create a pull request to reorder `mkdocs.yml` to match that. Anyone interested can then see what it would look like in the docs, via the Cloudflare Pages preview that is linked in the pull request.

**Comment by HelenCEBM** [comment]
Thanks @annaschultze & @wjchulme for helpful comments. 

Here's the suggested structure: https://github.com/opensafely/documentation/pull/392

**Comment by StevenMaude** [comment]
#392 was merged and the structure was much improved, so closing this.

If there's more restructuring following that, this probably should be a separate issue.
