### ISSUE TITLE
Find a workaround for Dependabot security updates limitation

### ISSUE THREAD

**Issue by madwort** [opensafely/documentation#275]
Currently dependabot security updates does not run correctly, e.g. [this log](https://github.com/opensafely/documentation/security/dependabot/requirements.txt/Pillow/open/update-logs/132029031). 

I think this is because this repo requires `opensafely-cohort-extractor` to extract docstrings, which means that the requirements file also includes secondary dependencies such as numpy etc, which require some system dependencies to be installed before installing the python packages. There's currently no way to install these external dependencies for Dependabot security updates (though Dependabot version updates is more flexible & I think it may be possible there).

**Comment by StevenMaude** [comment]
@madwort: does the pinning of `.python-version` in #321 for the non-security updates fix this, and if so can we close this one? :grin:

**Comment by madwort** [comment]
@StevenMaude yes I can't see the log either, must have been garbage-collected. I previously thought that dependabot-security-updates ran in a different way & wouldn't accept configuration such as python version pinning, but hopefully we can pick up the updates through dependabot-version-updates anyway. I reckon let's close this for now & re-open if it becomes a problem.
