### ISSUE TITLE
Improve Python installation guidance on macOS

### ISSUE THREAD

**Issue by StevenMaude** [opensafely/documentation#280]
@CarolineMorton and I had a feedback session with a user today. They couldn't complete the Getting Started guide because they encountered issues with Python. The `pyenv` steps seems incomplete and we're not sure it's entirely necessary by default.

**Comment by ghickman** [comment]
@StevenMaude @CarolineMorton – did you find out what issues they encountered?  Or where the pyenv steps fell over?  Am I right in thinking they were following the instructions on [this page](https://docs.opensafely.org/install-macos/)?

I'm fairly sure I can see which part of the pyenv docs are incomplete already (no setting up of the shims), but would be good to get more insight.

**Comment by StevenMaude** [comment]
@ghickman: We were watching the user as they ran the steps. If I recall correctly, the `pipx` install worked fine, and repeating this said that `opensafely` was already installed.

But `opensafely` was subsequently not found in the path. I think it was just a generic `command not found` error. I haven't used pyenv, so I didn't know (quickly) how to switch to the correct Python environment to then run the commands.

We just gave up on this after 10 minutes and @CarolineMorton suggested to just use a Python virtualenv. Python 3.9 was installed, I think.

Perhaps @CarolineMorton remembers a little more.

**Comment by ghickman** [comment]
Ah! I see the issue, we need a step which either sets up the pipx directory in their path or to modify the opensafely command to `pipx run opensafely`.  I would opt for the former since it should create a lower support burden long term.
