### ISSUE TITLE
Update mkdocs-related dependencies

### ISSUE THREAD

**Issue by StevenMaude** [opensafely/documentation#314]
* mkdocs
* mkdocstrings
* mkdocs-material

It looks like these were added around October 2020. That's based on the mkdocstrings and mkdocs-material versions in `requirements.txt`.

So probably due an update for slight improvements and bug fixes. A quick look of the changelogs for each doesn't suggest problems with doing so.

**Comment by madwort** [comment]
this repo has dependabot-security-updates enabled, should we also enable dependabot-version-updates?

**Comment by StevenMaude** [comment]
> this repo has dependabot-security-updates enabled, should we also enable dependabot-version-updates?

Sounds good to me :+1: I didn't know dependabot-version-updates was a thing; [it's relatively new](https://github.blog/changelog/2021-03-31-dependabot-version-updates-are-now-generally-available/).

The frequency of updates here shouldn't be too high.
