### ISSUE TITLE
button to move forward/back to the next/previous page

### ISSUE THREAD

**Issue by wjchulme** [opensafely/documentation#33]
To help with navigation. This is especially helpful when viewing on a mobile or in a narrow window because the navigation menu to the left disappears.

**Comment by madwort** [comment]
Hmmm, I'm not sure I follow - it has some buttons like this at the very bottom of the pages, e.g. on https://docs.opensafely.org/en/latest/git/ it has a link to the next page "Installing Python" 
<img width="1317" alt="Screenshot 2020-11-10 at 21 52 04" src="https://user-images.githubusercontent.com/2082895/98738156-2efc7000-239f-11eb-83a1-f56f0b5cb0fe.png">

**Comment by wjchulme** [comment]
Oh yes! it's there. You just have to scroll down to the bottom for it to appear. Don't really see any problem with this
