### ISSUE TITLE
Integrate data ingestion dates

### ISSUE THREAD

**Issue by sebbacon** [opensafely/documentation#34]
Somehow, we want to get the information from [this notebook](https://github.com/opensafely/rapid-reports/blob/master/notebooks/latest-dates.ipynb) into the documentation.

The simplest iteration is to confirm we are allow to publish it without NHSE approval; then link to it from the docs.

The better iteration is to convert the notebook into a project pipeline (this will also require study definition support for querying build time metadata from the backend); get it to output the result as markdown, and write that directly to this repo (via a PR).

**Comment by amirmehrkar** [comment]
commented here for now https://ebmdatalab.slack.com/archives/C010SJ89SA3/p1605802048341900?thread_ts=1605539400.205400&cid=C010SJ89SA3 @sebbacon

**Comment by Bengoldacre** [comment]
while you're here, the link needs replacing i think https://github.com/opensafely/rapid-reports/blob/master/notebooks/latest-dates-v2.ipynb

**Comment by wjchulme** [comment]
I've put this notebook in a new repo, here https://github.com/opensafely/database-notebooks/blob/master/notebooks/database-builds.ipynb with a view to it containing a collection of notebooks about the data to be linked to in the documentation. 

@amirmehrkar has obtained green light from E to publish

**Comment by wjchulme** [comment]
*Update*

I tried to get [this notebook-to-markdown](https://github.com/opensafely/database-notebooks/blob/master/markdown/database-builds/database-builds.md) page directly into the documentation using `mkdocs-snippets-plugin` but it didn't quite work -- see https://github.com/opensafely/documentation/pull/95#issuecomment-760945712

**Comment by sebbacon** [comment]
Yeh, I've taken a quick look at the plugin code and it's implemented in a buggy way. We want to support this so for Short Data Reports microsite too, so I suggest we write our own plugin (when? I'm not sure...)

**Comment by StevenMaude** [comment]
@sebbacon: Reviewing this old issue, the current state is:

* the new-since-this-issue-was-originally-opened reports site contains the [database report](https://reports.opensafely.org/reports/opensafely-tpp-database-builds/)
* the [documentation site](https://docs.opensafely.org/data-sources/systmone/#opensafely-tpp-database-coverage-and-metadata) links to the database report

Is there anything else needed here? Would we still want to integrate this data more tightly into the docs site?
