### ISSUE TITLE
include_month description incorrectly refers to days

### ISSUE THREAD

**Issue by ciaranmci** [opensafely/documentation#359]
The description of the include_month argument in the [Variable Reference ](https://docs.opensafely.org/study-def-variables/#cohortextractor.patients.with_these_clinical_events) page incorrectly refers to "day" instead of "month". 
The description should read "a boolean indicating if **month** should be included in addition to year (deprecated: use date_format instead)".

I appreciate that that include_month argument is now depreciated so this isn't going to be a top priority.

**Comment by StevenMaude** [comment]
Thanks for highlighting these @ciaranmci, it's appreciated! They definitely help reduce confusion or surprise for anyone else reading in future.

In case it's unclear, the variable reference text is generated from the docstrings in the [cohort-extractor](https://github.com/opensafely-core/cohort-extractor) repository. Once the associated issue is merged in cohort-extractor, we have to upgrade to a new version of cohort-extractor here in this repository. Then you'll be able to finally see the fixes on the [docs site](https://docs.opensafely.org/study-def-variables/).

We have a regular upgrade check running, so these changes should show up in the next day or two :slightly_smiling_face:

**Comment by ciaranmci** [comment]
Thanks, @StevenMaude.

I'll close this issue in a day or two after I confirm the change has gone through. I don't doubt that it will; I'm just offering a second pair of eyes.
