### ISSUE TITLE
Age can be negative

### ISSUE THREAD

**Issue by sebbacon** [opensafely/documentation#37]
In `age_as_of`, if a patient is born after the index date, you can have a negative age.

I think this is probably desirable behaviour but we should at least document this.

Perhaps we should add a flag to the method with `include_born_after` or something as well?

**Comment by alexwalkercebm** [comment]
I agree that it's fine to be negative.

Most studies that I've been involved with have excluded on age using something like:
```py
population=patients.satisfying(
    """
    age >=18 AND age <= 110
    """
)
```
so I don't think the `include_born_after` method is urgent.

**Comment by sebbacon** [comment]
Now documented.

**Comment by wjchulme** [comment]
here: https://github.com/opensafely/cohort-extractor/blob/5f12ed792305743799dee88cc2f27ee2abfc4791/cohortextractor/patients.py#L67
