### ISSUE TITLE
Dates in return_expectations don't seem to accept date expressions

### ISSUE THREAD

**Issue by jscuffell** [opensafely/documentation#389]
Hi there,

I've just started having a go at using Opensafely to generate dummy data to use to plan the data analysis for a separate project.  Apologies if I'm misunderstanding what index_date does or it's my study definition code, but I'm getting some inconsistent behaviour with the date in return_expectations. My current study definition is below:

```
from cohortextractor import (
    StudyDefinition,
    codelist,
    codelist_from_csv,
    combine_codelists,
    filter_codes_by_category,
    patients,
)
from codelists import *

def loop_over_codes(code_list):
    def make_variable(code):
        return {
            f"{code}": (
                patients.with_these_clinical_events(
                    codelist([code],system="snomed"),
                    on_or_after="index_date",
                    returning="date",
                    find_first_match_in_period = True,
                    date_format="YYYY-MM-DD",
                    return_expectations={
                        "date": {"earliest": "2004-01-01", "latest": "today"}, # this date expression
                        "rate" : "uniform",
                    },
                )
            )
        }

    variables = {}
    for code in code_list.keys():
        variables.update(make_variable(code))
    return variables

study = StudyDefinition(
    default_expectations={
        "date": {"earliest": "2004-01-01", "latest": "today"},
        "rate": "uniform",
        "incidence": 0.2,
    },
    population = patients.all(),
    index_date = "2021-09-01",
    
    age = patients.age_as_of("index_date",
                            return_expectations = {"int" : {"distribution": "population_ages"}, "incidence" : 1}),
    
    sex=patients.sex(
        return_expectations={
            "rate": "universal",
            "category": {"ratios": {"M": 0.49, "F": 0.51}},
        }
    ),
    
    **loop_over_codes(codelists),
)
```

When I do a opensafely run run_all, the cohortextractor does not return any data for the variables which have been created in the make_variable loop (first few lines of input.csv below):

> cancer1,cancer3,bornlatam,dementia,cancer2,smi,ckd35,asthma,age,sex,patient_id
>,,,,,,,,39,M,911661
>,,,,,,,,38,F,571755
>,,,,,,,,36,F,681666
>,,,,,,,,44,F,369185
>,,,,,,,,8,F,524457
>,,,,,,,,44,F,983471
>,,,,,,,,14,F,876029

Interestingly, if I change the 'earliest' parameter in return_expectations from '2004-01-01' to 'index_date', it works as expected:

>cancer1,cancer3,bornlatam,dementia,cancer2,smi,ckd35,asthma,age,sex,patient_id
>,2021-09-02,,,,,,,42,F,389551
>,,,,,,,,64,F,287564
>,,,,,,,,61,F,580975
>,,,,,,,2021-09-02,4,F,212551
>2021-09-02,,,2021-09-02,,2021-09-02,2021-09-02,,64,M,250708

It's no problem - I can just change the index_date - but wondered if this was the correct behaviour?

Many thanks,
Jamie

**Comment by StevenMaude** [comment]
@jscuffell: :wave: thanks for your question! I'm not personally familiar enough with the cohort-extractor to give an answer without digging.

Because this is more of a usage question, I've copy-pasted [it to our discussion forum](https://github.com/opensafely/documentation/discussions/393) for visibility where others in OpenSAFELY are more likely to see it :eyes: and will close this issue in favour of that.

Hopefully someone can give you an answer after the weekend!
