### ISSUE TITLE
How to Request Extra R Packages

### ISSUE THREAD

**Issue by ghickman** [opensafely/documentation#43]
From Seb in Slack:

> Make an issue  in https://github.com/opensafely/r-docker; explain the rationale; get another member of the suppoRt group to chip in on the issue (e.g. do they agree; do they think a different package might do the same thing better); assign to @simon when discussion finished

**Comment by wjchulme** [comment]
merged but I've now moved it to a different section on feature requests and bug reports, in this PR https://github.com/opensafely/documentation/pull/49

Should be viewable here: https://docs.opensafely.org/en/latest/requests-packages/
