### ISSUE TITLE
Distinguish between remote and face to face consultations

### ISSUE THREAD

**Issue by v1kki213** [opensafely/documentation#430]
Is it possible, or will it be possible to distinguish if a consultation is remote (i.e. over the phone) or face to face in either TPP or EMIS or both systems? 
Being able to define this would give more detailed information about how COIVD has impacted on care pathways for different conditions, and indeed variability in outcomes for these conditions based on consultation mode.

**Comment by StevenMaude** [comment]
@v1kki213: :wave: thanks for the suggestion.

I've closed this issue and opened https://github.com/opensafely-core/cohort-extractor/issues/661 for visibility, because this feels like a cohort-extractor feature request.
