### ISSUE TITLE
server error (500) when discarding draft codelist

### ISSUE THREAD

**Issue by rmgpanw** [opensafely/documentation#439]
I get a webpage saying 'server error (500)' when I discard a draft codelist. The codelist draft is successfully removed, but ideally there wouldn't be the error page? Thanks

**Comment by StevenMaude** [comment]
@rmgpanw: thanks for reporting this. Because this relates to OpenCodelists, I'm closing this issue and have opened it [in the opencodelists repository](https://github.com/opensafely-core/opencodelists/issues/922).
