### ISSUE TITLE
Example code for Measures not running locally 

### ISSUE THREAD

**Issue by annaschultze** [opensafely/documentation#47]
Not an urgent issue at all - but I'm struggling to get copied and pasted example code from the documentation to run locally as cohortextractor is throwing errors when expectations are not specified. This impacts the example code for `Measures` here https://docs.opensafely.org/en/latest/measures/ . 

If this is the way cohortextractor works rather than just me (possible!), we may want to add something to study definition explaining the need for expectations + update the code so that people are able to run this when trying things out.

**Comment by wjchulme** [comment]
thanks, fixed by https://github.com/opensafely/documentation/pull/54
