### ISSUE TITLE
clarify differences in column order WRT dummy data and the backends

### ISSUE THREAD

**Issue by andrewscolm** [opensafely/documentation#489]
The column index of a variable may not be consistent between the dummy data and the backend. Suggest an addition to the [docs](https://docs.opensafely.org/actions-pipelines/) to clarify this. Something along the lines of 

> * The ordering of columns may not be consistent between the dummy data and the TPP/EMIS backend. You should avoid referring to index integer positions and instead use the index names.

**Comment by andrewscolm** [comment]
https://github.com/opensafely/documentation/pull/490

**Comment by HelenCEBM** [comment]
Could also mention that it may change as variables are added/removed (in case that's not obvious) or with different versions of cohortextractor?

**Comment by StevenMaude** [comment]
Fixed by #490.
