### ISSUE TITLE
Macs and python 2 

### ISSUE THREAD

**Issue by CarolineMorton** [opensafely/documentation#5]
Just a reminder to myself that macbooks (unless v new version) come preloaded with python 2 and need to use `python3` after installation on the command line. This may also cause issues with pip if pip trying to install to the wrong python version. option include:

`pip3 install [package]`

or my preferred

`python3 -m pip install [package]`

Just had this issue with Rohini's mac and had to screenshare to fix.

**Comment by kevwing** [comment]
For the “not yet documented” bit under Mac users - the link under “follow these instructions” takes you to a page that includes instructions for installing Anaconda on a Mac.

Also could include under the Mac users but that Mac users don’t need to use Anaconda prompt, but should just use the Mac terminal - it already has the ability to find pip.

**Comment by CarolineMorton** [comment]
From memory, I think you still have to install Pip for Python3 otherwise it will use go to Python 2 I think. Would be good to confirm on a fresh mac book, what the basic set up as err.. its been a while for me!

**Comment by ghickman** [comment]
Current macOS instructions detail how to install a modern Python, combined with Apple shipping Python 3 for at least one OS version now, I think this one is done 🎉
