### ISSUE TITLE
Docker login needed first time running stata-mp

### ISSUE THREAD

**Issue by CarolineMorton** [opensafely/documentation#66]
@rohinimathur has been working through the documentation and ended up hitting an error with `cohortextractor run dummy run_all expectations` (which is [here](https://docs.opensafely.org/en/latest/pipelines/#running-your-code-locally) in the docs). 

The error messages show that the issue is that `stata-mp` is behind a password on `ghcr.io/opensafely`. There is mention is in the docs and a link out to https://github.com/opensafely/server-instructions/blob/master/docs/Server-side%20how-to.md#log-in-to-docker. 
Just to check with @bloodearnest, that this is expected?? I think it should already be authorised or logged in on the server but presumably this is expected on peoples' local machines?

I think in the next iteration of the documentation could be made more prominent that this is something likely to happen the first time you are running this. 

In addition the link, needs to have an updated docker registry - from `docker.opensafely.org` to `ghcr.io/opensafely`.

**Comment by CarolineMorton** [comment]
Have made a PR to change the server instructions

**Comment by evansd** [comment]
Thanks @CarolineMorton. This is expected for now but going to change soon so that as long as you're a member of the opensafely GitHub org it should all just work. Simon's done most of the work already for this.

**Comment by wjchulme** [comment]
@bloodearnest I think this one be closed?

**Comment by bloodearnest** [comment]
It is, thanks
