### ISSUE TITLE
"CodedEvent_SNOMED" error but codelist hasn't changed

### ISSUE THREAD

**Issue by ciaranmci** [opensafely/documentation#673]
Today I re-ran a script on the job server ([job ID: x5tvqrb4lpuiapa](https://jobs.opensafely.org/university-of-leeds/cancer-surgery-service-evaluation/all_cause_mortality_with_stratification/6577/x5tvqrb4lpuiapam/)) and, for the first time, my `generate_study_population` script failed citing an error code about "CodedEvent_SNOMED".
I assume this refers to the `CodedEvent` table in the cohortextractor (but I'm only basing this assumption on [the only reference to "CodedEvent" that I could find](https://github.com/opensafely/documentation/issues/114)).

My scripts run perfectly well on my local OpenSAFELY docker container, and my codelist hasn't changed since my most-recent successful run ([job ID: akakanz4oqjuokq4](https://jobs.opensafely.org/university-of-leeds/cancer-surgery-service-evaluation/all_cause_mortality_with_stratification/6514/akakanz4oqjuokq4/)).

**Questions:**

1. Can you direct me to the CodedEvent table in the hope that I might be able to cross check my codelist for possibly-missing code?
2. Do you have any ideas about what might suddenly have started causing this?

**Comment by StevenMaude** [comment]
@ciaranmci: :wave: I've moved this to the [discussions Q&A](https://github.com/opensafely/documentation/discussions/675) for better visibility.

Closing this issue to avoid any duplication.
