### ISSUE TITLE
Use of open safely for custom non medical dataset

### ISSUE THREAD

**Issue by vidit2011998** [opensafely/documentation#699]
Hello,
I would like to know if open safely can be used to run custom non medical dataset?
If yes, could you tell in short what changes I should make to achieve that?

Thank you

**Comment by StevenMaude** [comment]
:wave: @vidit2011998: OpenSAFELY is designed specifically for researchers to query healthcare datasets without needing access to the underlying raw data.

There may be other more suitable trusted research environment platforms that can handle a non-medical, sensitive dataset you want to work with.
