### ISSUE TITLE
Write a more comprehensive ehrQL tutorial

### ISSUE THREAD

**Issue by StevenMaude** [opensafely/documentation#739]
*Originally posted on [Shortcut](https://app.shortcut.com/ebm-datalab/story/771/write-a-more-comprehensive-ehrql-tutorial); placing here so it's not lost*

This might be an iteration on @inglesp's [tutorial for a previous design of the DSL](https://github.com/opensafely-core/databuilder/pull/297)

"As a technically competent OpenSAFELY user, I want a tutorial that gives me sufficient understanding of core concepts to be able to make more sense of the other ehrQL material."

**Comment by StevenMaude** [comment]
I am creating several issues to reflect what's needed; this could be a TODO list for those issues, or be closed.

**Comment by benbc** [comment]
@StevenMaude This breakdown looks good.

I suggest adding one more issue along the lines of "Make it easy for researchers to modify the tutorial data definition and run it locally against the mock sample data". Firstly this is a good goal and we should explicitly record it. Secondly putting it into a separate issue allows us to defer work that specifically meets this goal, so we may be able to deliver other parts of the work sooner.

**Comment by StevenMaude** [comment]
Closing this issue in favour of the [others linked above](https://github.com/opensafely/documentation/issues/739#issuecomment-1170209702).
