### ISSUE TITLE
Update surrounding documentation to refer to ehrQL

### ISSUE THREAD

**Issue by StevenMaude** [opensafely/documentation#743]
*Originally posted on [Shortcut](https://app.shortcut.com/ebm-datalab/story/333/update-introductory-and-other-documentation-once-everything-is-in-place); placing here so it's not lost*

(There's no other content here.)

**Comment by StevenMaude** [comment]
This still needs to remain in this repository. The update here refers mainly to:

* explaining that Data Builder as a core part of OpenSAFELY over cohort-extractor in introductory documentation
* adding a warning to cohort-extractor pages to mention it is deprecated, and users should consider Data Builder for new studies
* switching to Data Builder in the Getting Started guide

**Comment by inglesp** [comment]
Closing in favour of https://github.com/opensafely-core/ehrql/issues/1676/.

**Comment by StevenMaude** [comment]
Actually closing this issue :wink:
