### ISSUE TITLE
Add description of ehrQL classes to reference docs

### ISSUE THREAD

**Issue by inglesp** [opensafely/documentation#771]
The reference docs should include descriptions of each of these classes defined in [query_language.py](https://github.com/opensafely-core/databuilder/blob/main/databuilder/query_language.py), and an explanation of how they relate to each other:

* `Dataset`
* `PatientFrame`
* `PatientSeries`
* `EventFrame`
* `EventSeries`
* `SortedEventFrame`

We don't need to include descriptions of the methods available on each class, since this should be provided by the documentation generated from the spec tests.

Beyond enumerating the subclasses of `PatientSeries`/`EventSeries`, I don't think there's any need to document them in detail.

The descriptions could be extracted from docstrings, but we must ensure that documentation for users and documentation for developers are kept separate.

**Comment by StevenMaude** [comment]
Moved to opensafely-core/databuilder#1043.
