### ISSUE TITLE
Add narrative to each section of reference docs

### ISSUE THREAD

**Issue by inglesp** [opensafely/documentation#773]
Most (if not all) chapters and sections of the ehrQL reference docs would benefit from a narrative description of the behaviour that is demonstrated in the example.

For example, [2 Picking one row for each patient from an event frame](https://docs.opensafely.org/ehrql-reference/#2-picking-one-row-for-each-patient-from-an-event-frame) should include _something_ like:

> An `EventFrame` can be reduced to a `PatientFrame` by picking one row of the `EventFrame` for each patient.  To identify a row to pick, you must first sort the rows for each patient by the values in one or more columns, and then choose either the first or last row for each patient.
>
> Calling `.sort_by()` on an `EventFrame` returns a `SortedEventFrame`, and the only thing you can do with a `SortedEventFrame` is pick one row per patient to return a `PatientFrame`.

This depends on #772, although work could begin before #772 is finished.

**Comment by StevenMaude** [comment]
Moved to opensafely-core/databuilder#1045.
