### ISSUE TITLE
Reduce duplication of tables in reference docs

### ISSUE THREAD

**Issue by inglesp** [opensafely/documentation#776]
For instance, [2.1.1 Sort by column pick first](https://docs.opensafely.org/ehrql-reference/#211-sort-by-column-pick-first) and [2.2.1 Sort by column pick last](https://docs.opensafely.org/ehrql-reference/#221-sort-by-column-pick-last) use the same table.

Instead of showing the table twice, we should show it once, under the heading [2 Picking one row for each patient from an event frame](https://docs.opensafely.org/ehrql-reference/#2-picking-one-row-for-each-patient-from-an-event-frame).

This will involve changing [databuilder/docs/specs.py](https://github.com/opensafely-core/databuilder/blob/main/databuilder/docs/specs.py) and the [mkdocs plugin](https://github.com/opensafely-core/mkdocs-opensafely-databuilder/blob/main/plugin/specs.py).

**Comment by StevenMaude** [comment]
Moved to https://github.com/opensafely-core/databuilder/issues/1032.
