### ISSUE TITLE
Add structure to URLs of databuilder docs

### ISSUE THREAD

**Issue by inglesp** [opensafely/documentation#777]
The URL structure of the OpenSAFELY documentation is currently flat.  It would be neater (and would make the docs source code easier to navigate) if the URLs were nested.  For instance:

| old | new |
|-|-|
| https://docs.opensafely.org/data-builder-toc/ | https://docs.opensafely.org/data-builder/ |
| https://docs.opensafely.org/ehrql-intro/ | https://docs.opensafely.org/data-builder/ehrql/ |
| https://docs.opensafely.org/ehrql-tutorial/ | https://docs.opensafely.org/data-builder/ehrql/tutorial/ |

We can start with the databuilder (or is it data-builder?) docs since these are unused and we don't have to worry about redirects.

**Comment by StevenMaude** [comment]
Something like @inglesp's idea could work is definitely one good option.

We could consider the site's entire URL structure first (#717).

We could add redirects here in case anyone internally has these links bookmarked, perhaps, maybe just temporarily if they are not linked/indexed anyway. But it's also fine to break the links as they are internal use only.

**Comment by StevenMaude** [comment]
What we have at the moment:

```
data-builder-dummy-data.md
data-builder-intro.md
data-builder-quick-start.md
data-builder-toc.md
data-builder-versioning.md
data-builder-vs-cohort-extractor.md
```

```
ehrql-combining-series-and-frames.md
ehrql-examples.md
ehrql-intro.md
ehrql-new-tutorial-1a.md
ehrql-new-tutorial-1b.md
ehrql-new-tutorial-2a.md
ehrql-new-tutorial-3a.md
ehrql-new-tutorial-4a.md
ehrql-new-tutorial-5a.md
ehrql-new-tutorial-6a.md
ehrql-new-tutorial-7a.md
ehrql-new-tutorial-conclusion.md
ehrql-new-tutorial-intro.md
ehrql-new-tutorial-opensafely-project.md
ehrql-new-tutorial-python.md
ehrql-reference.md
ehrql-set-population-explainer.md
```
