### ISSUE TITLE
Describe codelists helpfully in reference docs

### ISSUE THREAD

**Issue by inglesp** [opensafely/documentation#778]
This issue is part of [this](https://docs.google.com/document/d/1vjl4c16CDw0oJy9PQt7kQoammofeQrqzdIN_SrCunXg) initiative. You should familiarize yourself with how the reference doc generation works before starting on this issue; several people on the team can help with this.

The display of codelists in the reference docs is not enormously helpful. Codelists are an important special case, so it's worth investing some effort in making the docs that refer to them as useful as possible. The relevant docs are [here](https://docs.opensafely.org/ehrql-reference/#9-operations-on-all-series-containing-codes), they are generated from specs [here](https://github.com/opensafely-core/databuilder/tree/main/tests/spec/code_series_ops).

For a spec where the contents of a codelist is important, we would like the generated reference doc to look something like this:

---

This example makes use of a patient-level table named `p` containing the following data:

patient | c1
-- | --
1 | 11111111
2 | 22222222
3 | 33333333
4 |  

This example also makes use of a SNOMED-CT codelist named `c` containing the following codes: 11111111, 33333333.

```
p.c1.is_in(c)
```

returns the following patient series:

[...]

---

To achieve this we need to add an optional `codelists` argument to `spec_test()` which takes a mapping of names to codelists. (This won't actually be used when running the tests, but it's needed for doc generation which inspects the arguments to `spec_test()`.) Then the name, system and values of any codelists are extracted during spec extraction. Finally descriptive prose is assembled at doc generation time.

You will also need to come up with an elaboration on this which works for codelist categorization.

Finally, please modify the codelist containment tests to remove the duplication between tests that construct the codelists explicitly from `BaseCode` objects and those that use `codelist_from_csv_lines()`. Researchers will always be reading codelists from disk, so the different ways of constructing them aren't interesting to them. (And the specs aren't a good way to unit test the different construction methods.)

**Comment by benbc** [comment]
@inglesp Is this in the spec docs?

**Comment by benbc** [comment]
I think there are potentially also "reference" docs for things that aren't ehrQL and therefore won't be generated from the specs. (For example the codelist-handling functions, but also measures, dummy data eventually.)

**Comment by benbc** [comment]
@inglesp Do you have any idea what the desired behaviour is here? Current reference content involving codelists is [here](https://docs.opensafely.org/ehrql-reference/#9-operations-on-all-series-containing-codes).

**Comment by inglesp** [comment]
How about something like:

---

This example makes use of a patient-level table named `p` containing the following data:



patient | c1
-- | --
1 | 11111111
2 | 22222222
3 | 33333333
4 |  

This example also makes use of a SNOMED-CT codelist named `c` containing the following codes: 11111111, 33333333.

**Comment by Jongmassey** [comment]
Am I right in thinking that the descriptive prose changes will be made in https://github.com/opensafely-core/mkdocs-opensafely-databuilder ?

**Comment by inglesp** [comment]
After discussion with @Jongmassey I'm closing this, because the problematic part of the docs, [9.1.3 Is in codelist csv](https://docs.opensafely.org/ehrql-reference/#913-is-in-codelist-csv), are generated from [a redundant test](https://github.com/opensafely-core/databuilder/blob/main/tests/spec/code_series_ops/test_containment.py#L45-L66) -- [this test](https://github.com/opensafely-core/databuilder/blob/main/tests/spec/code_series_ops/test_containment.py#L19-L29) already covers the relevant behaviour of ehrQL and the QM.

The spec tests shouldn't care about where a codelist has come from (much like how they shouldn't care about date objects or strings).  We should test that loading a codelist from a CSV works in a unit test that doesn't touch the QM, and we should document how to do this outside the spec tests.  @Jongmassey's going to create the ticket for this work.
