### ISSUE TITLE
Placeholder: Add mechanism to show invalid ehrQL constructs in reference docs

### ISSUE THREAD

**Issue by inglesp** [opensafely/documentation#779]
The reference docs should include examples of invalid ehrQL constructs with error messages and an explanation of why the construct is invalid.

Examples might include:

* trying to do a series operation on a frame, or vice versa
* trying to do an invalid operation on a series
* trying to set a non-`PatientSeries` as an attribute (or population) on a `Dataset`

**Comment by benbc** [comment]
@inglesp Any chance of fleshing this out a bit?

**Comment by inglesp** [comment]
Thanks for the reminder @bebnc.  I've added some more details about what this ticket is trying to solve.  I can add some implementation notes if we think it is worth doing.

**Comment by StevenMaude** [comment]
Moved to opensafely-core/databuilder#1049.
