### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ghickman** [opensafely/documentation#80]
We have a broken link on the [Security page](https://docs.opensafely.org/en/latest/security-levels/) as per https://twitter.com/frabcus/status/1343857731636224000

**Comment by madwort** [comment]
oooh, at the same time, please bear in mind the university's guidance on links:
```
Links 
∙ Links should be meaningful out of context and make sense without reading surrounding text. 
∙ Do not use link text such as ‘Click here’, ‘Read more’ or ‘Find out more’
∙ Links should be embedded within text, not typed in full. For example, ‘To find out more, visit  https://www.medsci.ox.ac.uk/accessibility’ should be ‘To find out more, read our Accessibility  Statement’. 
∙ External links should always open in the same window. Further guidance is available here. 
```
which I think means something like `The schema for this database can be seen *here*` -> `Please take a look at *the schema for the database*`
