### ISSUE TITLE
enable markdown formatting inside <details>

### ISSUE THREAD

**Issue by wjchulme** [opensafely/documentation#81]
eg the "click here to expand" link on this page https://docs.opensafely.org/en/latest/releasing-files/ doesn't format markdown lists correctly, even though it does when rendered here https://github.com/opensafely/documentation/blob/master/docs/releasing-files.md. Something to do with mkdocs

**Comment by madwort** [comment]
nb. anchor text is now `Click here to read in more detail about the `osrelease` command.`

**Comment by madwort** [comment]
Fixed - required two things: installing a plugin, and updating the opening details tag to look like `<details markdown="1">` - see these docs for more info & options https://python-markdown.github.io/extensions/md_in_html/
