### ISSUE TITLE
create single linkable page or section with overview of data sources

### ISSUE THREAD

**Issue by wjchulme** [opensafely/documentation#822]
From @Bengoldacre: https://bennettoxford.slack.com/archives/C31D62X5X/p1656065228481669

> the problem is the things you'd naturally like to link to are folders in the nav with rotating arrows, not pages ("Data sources" and maybe "Externally linked data") 

So we would like an additional section that links to all available data sources available on each backend. An overview of _all_ available data sources across _all_ backends on a single page doesn't quite fit with the existing structure of backend-specific pages (eg [for TPP](https://docs.opensafely.org/dataset-systmone/)) but that's ok -- it can go on the [overview](https://docs.opensafely.org/dataset-intro/) page as a nested list like this:

* OpenSAFELY-TPP
  * SystmOne primary care
  * SUS hospital admissions
  * SUS outpatients
  * death register
  * ...
* OpenSAFELY-EMIS
  * EMIS primary care
  * ?
* (other future operational backends)
  * data

**Comment by sebbacon** [comment]
Can this requirement be serviced with some kind of ToC widget that replicates how things work in the primary navigation, and causes the ToC to be displayed under some page-specific top matter?

Ben has previously asked for the same thing with respect to other sections, too.

**Comment by rebkwok** [comment]
I'm looking, but I haven't found anything so far
