### ISSUE TITLE
Expand on the current tutorial to demonstrate ehrQL concepts

### ISSUE THREAD

**Issue by StevenMaude** [opensafely/documentation#834]
# Goal

The existing ehrQL reference, based on the specification tests, is good at describing behaviours, but does not make an attempt to explain them.

The current tutorial was written as a placeholder. We should now extend the existing placeholder tutorial.

# Tasks

This requires:

* determining the core ehrQL concepts a user needs to understand, and those that can be ruled out
* developing a simple example dataset (details in #833) to use in the tutorial
* writing simple ehrQL examples that demonstrate those concepts
* writing surrounding explanatory text
* the surrounding text on `https://docs.opensafely.org/ehrql-intro` modifying, as the tutorial will change; we can leave the simple example as is.

This could be completed independently of fully integrating the tutorial into this documentation (#835). It would be sufficient, though not ideal, to include code initially as static Markdown content [^1].

[^1]: A longer-term goal should be to require that any working code examples in newly added documentation is suitably tested, just as we typically expect newly added software code is suitably tested.

**Comment by StevenMaude** [comment]
## Potential ehrQL concepts to cover

* The current ehrQL interface is based on Python. 
* `Frames`, `Series`
  * It may be worth mentioning the insipiration of terminology from pandas.
* … :thought_balloon:

**Comment by StevenMaude** [comment]
Feedback collected from various comments:

* Perhaps to use a full `project.yaml` instead of just a dataset definition.
* Include learning objectives and small assessments.
* Cut down on admonitions where possible.
* Consider use of collapsible blocks for admonitions.
* Review what needs to be include; do we need to explain everything?

**Comment by inglesp** [comment]
> Review what needs to be include; do we need to explain everything?

Is this at the level of reviewing which databuilder concepts need to be explained, or which extra stuff (eg black/isort/flake8) need to be explained?  (Or both?)

**Comment by StevenMaude** [comment]
> Is this at the level of reviewing which databuilder concepts need to be explained, or which extra stuff (eg black/isort/flake8) need to be explained? (Or both?)

Initially, I was thinking more "extra stuff" because that's primarily what I took from a comment that was made.

But I think it relates to everything. That should become clearer when people work through.

**Comment by StevenMaude** [comment]
I've combined the [feedback above](https://github.com/opensafely/documentation/issues/834#issuecomment-1245240118) into a checklist in #987.
