### ISSUE TITLE
Use correct form of "SNOMED" in text

### ISSUE THREAD

**Issue by StevenMaude** [opensafely/documentation#910]
Tracking here, as I'm not sure there's a better place as it affects multiple repositories.

- [x] documentation (#909)
- [x] `opensafely.org` (change proposed)
- [x] OpenSAFELY Interactive (opensafely-core/interactive.opensafely.org#374)
- [x] `bennett.ox.ac.uk` (change proposed)
- [x] OpenCodelists (https://github.com/opensafely-core/opencodelists/pull/1347)
- [x] OpenPrescribing (https://github.com/ebmdatalab/openprescribing/pull/3633)

There may be other sites too.

**Comment by brianmackenna** [comment]
Just to make clear SNOMED CT will be what we use most by default as we are referring to the terminology but by exception we may occasionally need to refer to SNOMED International (as the organisation that maintains the terminology and provides associated services) or in some very rare circumstances SNOMED RT (an old version)
