### ISSUE TITLE
OpenSAFELY introspection

### ISSUE THREAD

**Issue by iaindillingham** [opensafely/documentation#914]
This is @iaindillingham's proposal for shore leave, from 15 to 26 August. It's an issue in the documentation repository, because it's loosely about documenting our current practices. (And because I couldn't think of an alternative repository!)

---

I'd like to introspect the studies that are run on the OpenSAFELY platform. I mean *introspect* in the whimsical sense of *navel-gazing* 🙂.

As a minimum, I'd like to treat each job request as a "run" of a study. For each job request, I'd like to parse the associated _project.yaml_. I'd then like to record the types of the actions. Whilst most will be `cohortextractor` actions, I'm particularly interested in the numbers of `python`, `r`, and `stata` actions; and in the numbers of reusable actions.

I've written a proposal for a talk on reusable actions at the NHS-R conference, so knowing how many studies are using reusable actions, as well as how researchers use them, will be useful. As an example of how researchers use reusable actions, consider a study as a sequence of job requests: are reusable actions added and removed? how long-lived are they?

If there's time, I'd also like to compare the characteristics of PRs made within opensafely and within opensafely-core, as well as between these organizations. If we think of the former as being written by researchers, and the latter as written by developers, then we should be able to identify how the behaviour of researchers is similar to/different from developers. I'd like to emphasize that I'm **not** going to identify researchers/developers, and that I'm **not** going to identify ordinal differences in behaviour (better/worse), only ordinal differences (similar/different).

I intend to write a "reproducible analytic pipeline" for each investigation, using [Data Version Control](https://dvc.org/). After this shore leave, a researcher/developer should be able to clone the repository, provide any necessary configuration, and execute the investigation anew. Everyone enjoys navel-gazing occassionally, after all.

**Comment by benbc** [comment]
You might also (or instead) be interested in the number of _runs_ of different types of actions which should be available from the Job Server database and/or logs.

**Comment by bloodearnest** [comment]
Possibly of interest - I recently extracted a redacted dump of the prod postgresdb into a sqlite db for local analysis by @LisaHopcroft, who is looking at similar questions.

I think a local sqlite db, possibly w/datasette, makes for a very useful exploration tool.

**Comment by iaindillingham** [comment]
As I've finished shore leave, I'm going to close this issue.

Repo: https://github.com/opensafely-core/opensafely-introspection
Results: https://opensafely-core.github.io/opensafely-introspection/
