### ISSUE TITLE
Use correct form of dm+d in the text

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/documentation#917]
Similar to #910 I have noticed some inconsistent use of dm+d in the docs, for [example here](https://www.opencodelists.org/docs/ DM&D)

@StevenMaude would you be able to do the find and replace and I can check?

Should we also consider the replacement to be [dm+d](https://www.bennett.ox.ac.uk/blog/2019/08/what-is-the-dm-d-the-nhs-dictionary-of-medicines-and-devices/)?

**Comment by StevenMaude** [comment]
I've added this to the data team project board, to find a time to resolve it.
