### ISSUE TITLE
Update contracts-related documentation build following Data Builder refactor

### ISSUE THREAD

**Issue by StevenMaude** [opensafely/documentation#937]
There is an open Data Builder PR that extensively refactors how contracts and backends work: opensafely-core/databuilder#680

We'll need to update the documentation to reflect this.

The timing of this change requires the above PR merging first. We should investigate whether the changes in the above PR break the documentation build here.

**Comment by StevenMaude** [comment]
## Updating the automated documentation build

- [ ] Check whether a typical `public_docs.json` generated by the PR (that @evansd should be uploading here) can at least be incorporated into the docs, even if the output is not correct.
- [ ] (Optional) If not, get the mkdocs plugin to the state where the docs can build.
- [ ] Wrangle the `public_docs.json` to get the correct output. We may want one page per backend.

**Comment by evansd** [comment]
Here's the output of `just generate-docs`:
[public_docs.json](https://github.com/opensafely/documentation/files/9498282/public_docs.txt)

**Comment by StevenMaude** [comment]
![contracts-reference-modified-json](https://user-images.githubusercontent.com/3818079/188687289-fbd923ca-d4db-4b65-a7ef-bfa6c9f3923f.png)

Seems to build OK for me. The content is not correct, obviously, but that's OK. We can add another disclaimer to the page pointing to this issue, until it's fixed.

**Comment by StevenMaude** [comment]
Moved to opensafely-core/databuilder#1050.
