### ISSUE TITLE
VPN setup for TPP Level 4 on mac with M2 silicon chip

### ISSUE THREAD

**Issue by eparker12** [opensafely/documentation#965]
Has anyone managed to get Level 4 server access on a new mac with an M2 silicon chip? If so, I'd be keen to know how you did it.

[This thread](https://github.com/opensafely/documentation/discussions/251) worked nicely for macs with intel chip, but VMWare fusion doesn't seem to be compatible on new M2 laptops.

**Comment by StevenMaude** [comment]
:wave: @eparker12 I've moved this question to the Discussions section for better visibility: #966

**Comment by eparker12** [comment]
Thanks so much @StevenMaude
